# Functions and variables {#functions-and-variables}

---


## Functions

The following list of functions is available. Each of these functions resides in the `BioNES.m` files (See brief description in Table \@ref(tab:core-directory)). Additionally, the `BioNES.m` file includes different callback functions associated with different sub-components of the GUI. These are self-explanatory with a brief explanation given in the function file itself.

Table: (\#tab:functions) List of available functions (GUI callback functions are not listed)

| SYNTAX                                            | DESCRIPTION                                                                                                           |
|---------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| `BioNES(varargin)`                                | Main function.                                                                                                        |
| `Help(varargin)`                                  | Holds the callback functions of the help GUI.                                                                         |
| `CalculateResults(handles)`                       | Calculates the final results like recorded session duration, sampling frequency, number of samples, and data quality. |
| `connectArduino(handles,string)`                  | Defines the logic to connect with the \`Arduino\` board.                                                              |
| `connectGame(handles)`                            | Connect with the `FCEUX` and start the game.                                                                          |
| `GuiStates(handles, string)`                      | Initialize the GUI sub-components as per various states.                                                              |
| `InitializeVariables(handles)`                    | Function file that initializes variable to their default state.                                                       |
| `logSys(handles, logString)`                      | Log system state for debugging.                                                                                       |
| `SetParam(handleName, string, color, handleType)` | Set color and text parameters for various GUI components.                                                             |


## Variables

The following variables are available in 3 categories. The variable names are self-explanatory.

Table: (\#tab:variables) List of available variables

| Settings                        | Data                           | Flags              |
|---------------------------------|--------------------------------|--------------------|
| `settings_daqDateTime`          | `data_relaxedHrv`              | `flag_isAcquiring` |
| `settings_sessionDate`          | `data_stressedHrv`             | `flag_isTimeRef`   |
| `settings_sessionTime`          | `data_sampleNumber`            |                    |
| `settings_customId`             | `data_timeStampsMsec`          |                    |
| `settings_sessionId`            | `data_ibi`                     |                    |
| `settings_sessionDuration`      | `data_beat`                    |                    |
| `settings_samplingRate`         | `data_dataRel`                 |                    |
| `settings_samplingTimeInterval` | `data_hrAvg`                   |                    |
| `setting_plotWidth`             | `data_hrvAvg`                  |                    |
| `settings_rightOffset`          | `data_playerState`             |                    |
| `settings_numberOfSamples`      | `data_isMainScreen`            |                    |
| `settings_serialPort`           | `data_gameMode`                |                    |
| `settings_ard`                  | `data_positionInLevel`         |                    |
| `settings_fceux`                | `data_score`                   |                    |
| `settings_xMin`                 | `data_recordedNumberOfSamples` |                    |
| `settings_xMax`                 | `data_recordedSessionDuration` |                    |
| `settings_yMin`                 | `data_recordedSamplingRate`    |                    |
| `settings_yMax`                 | `data_dataQuality`             |                    |
|                                 | `data_logSysData`              |                    |
